# https://alacritty.org/config-alacritty.html

import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Fullscreen"
decorations_theme_variant = "Dark"
padding = { x = 1, y = 0}

[font]
size = 16
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Regular" }
italic = { family = "FiraCode Nerd Font", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font", style = "Regular" }
offset = { x = 1, y = 0 }
glyph_offset = { x = 0, y = 0 }

[mouse]
hide_when_typing = true
