# https://alacritty.org/config-alacritty.html

import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Fullscreen"
decorations_theme_variant = "Dark"
padding = { x = 1, y = 0}

[font]
size = 16
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
offset = { x = 1, y = 2 }
glyph_offset = { x = 0, y = 0 }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
